**Depends on conda environment: Mito_Assemble (see .env/Mito_Assemble.yml)**

# 1

check the mitochondrial:

In [1]:
from pyfaidx import Fasta

Acer_fa = Fasta("./ref/GCF_029169275.1_AcerK_1.0_genomic.fna")

In [2]:
for name in Acer_fa.keys():
    print(name)

NC_083852.1
NC_083853.1
NC_083854.1
NC_083855.1
NC_083856.1
NC_083857.1
NC_083858.1
NC_083859.1
NC_083860.1
NC_083861.1
NC_083862.1
NC_083863.1
NC_083864.1
NC_083865.1
NC_083866.1
NC_083867.1
NW_026893558.1
NW_026893559.1
NW_026893560.1
NW_026893561.1
NC_014295.1

In [4]:
for name in Acer_fa.keys():
    print(f"{name}: {len(Acer_fa[name])}")

NC_083852.1: 27131825
NC_083853.1: 15875455
NC_083854.1: 13386827
NC_083855.1: 13159592
NC_083856.1: 13471485
NC_083857.1: 17285085
NC_083858.1: 13645534
NC_083859.1: 12170773
NC_083860.1: 11954044
NC_083861.1: 12434583
NC_083862.1: 15832348
NC_083863.1: 11302906
NC_083864.1: 11000381
NC_083865.1: 11731789
NC_083866.1: 9491825
NC_083867.1: 7109830
NW_026893558.1: 5207728
NW_026893559.1: 250740
NW_026893560.1: 93405
NW_026893561.1: 504434
NC_014295.1: 15895

## Search: https://www.ncbi.nlm.nih.gov/nuccore/NC_014295.1/ , indeed a mitochondria

# 2

Examine the CDS and exon start site:

In [ ]:
%%bash

gppy txinfo -g "./ref/GCF_029169275.1_AcerK_1.0_genomic.gtf" > "./metadata/Acer_txinfo.tsv"

# 失败原因是 transcript_id ""

Traceback (most recent call last):
  File "/home/liuzhiyu/Software/miniconda3/envs/Mito_Assemble/bin/gppy", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/liuzhiyu/Software/miniconda3/envs/Mito_Assemble/lib/python3.12/site-packages/gppy/gtf.py", line 735, in main
    tx_info(args.gtf, args.force_end_check)
  File "/home/liuzhiyu/Software/miniconda3/envs/Mito_Assemble/lib/python3.12/site-packages/gppy/gtf.py", line 548, in tx_info
    meta = tx_meta[tx_id]
           ~~~~~~~^^^^^^^
KeyError: ''

CalledProcessError: Command 'b'\ngppy txinfo -g "./ref/GCF_029169275.1_AcerK_1.0_genomic.gtf" > "./metadata/Acer_txinfo.tsv"\n'' returned non-zero exit status 1.

↑ The previous step failed; a suspected partial line contained the following: `transcript_id ""`

remove `transcript_id ""`:

In [40]:
%%bash

sed 's/transcript_id ""; //' "./ref/GCF_029169275.1_AcerK_1.0_genomic.gtf" > "./ref/GCF_029169275.1_AcerK_1.0_genomic_corrected.gtf"

Try regenerating Acer_txinfo.tsv

In [3]:
%%bash

gppy txinfo -g "./ref/GCF_029169275.1_AcerK_1.0_genomic_corrected.gtf" > "./metadata/Acer_txinfo.tsv"

In [1]:
import pandas as pd

In [4]:
Acer_info = pd.read_csv("./metadata/Acer_txinfo.tsv", sep="\t")
Acer_info

/tmp/ipykernel_76250/2624168542.py:1: DtypeWarning: Columns (0: codons, 1: locus_tag) have mixed types. Specify dtype option on import or set low_memory=False.
  Acer_info = pd.read_csv("./metadata/Acer_txinfo.tsv", sep="\t")

,tx_name,gene_id,chrom,strand,nexon,tx_len,cds_len,utr5_len,utr3_len,anticodon,...,gbkey,gene,inference,locus_tag,model_evidence,note,partial,product,protein_id,transcript_biotype
0,XM_017048878.3,LOC107992807,NC_083852.1,-,6,713,312,197,204,NaN,...,mRNA,LOC107992807,NaN,NaN,Supporting evidence includes similarity to: 13...,NaN,NaN,"ubiquitin-related modifier 1, transcript varia...",XP_016904367.1,mRNA
1,XM_017048879.3,LOC107992807,NC_083852.1,-,5,1167,312,651,204,NaN,...,mRNA,LOC107992807,NaN,NaN,Supporting evidence includes similarity to: 14...,NaN,NaN,"ubiquitin-related modifier 1, transcript varia...",XP_016904368.1,mRNA
2,XM_062082541.1,LOC107992805,NC_083852.1,+,6,4095,3759,155,181,NaN,...,mRNA,LOC107992805,NaN,NaN,Supporting evidence includes similarity to: 2 ...,NaN,NaN,MATH and LRR domain-containing protein PFE0570...,XP_061938525.1,mRNA
3,XM_062082566.1,LOC107992805,NC_083852.1,+,7,4344,3717,446,181,NaN,...,mRNA,LOC107992805,NaN,NaN,Supporting evidence includes similarity to: 1 ...,NaN,NaN,MATH and LRR domain-containing protein PFE0570...,XP_061938550.1,mRNA
4,XM_062082576.1,LOC107992805,NC_083852.1,+,7,4339,3675,483,181,NaN,...,mRNA,LOC107992805,NaN,NaN,Supporting evidence includes similarity to: 1 ...,NaN,NaN,MATH and LRR domain-containing protein PFE0570...,XP_061938560.1,mRNA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35198,unassigned_transcript_259,KEH14_p01,NC_014295.1,-,1,915,915,0,0,NaN,...,mRNA,ND1,NaN,KEH14_p01,NaN,NaN,NaN,NaN,YP_003735181.1,mRNA
35199,unassigned_transcript_260,KEH14_t21,NC_014295.1,-,1,69,0,0,0,NaN,...,tRNA,NaN,NaN,KEH14_t21,NaN,NaN,NaN,tRNA-Leu,NaN,tRNA
35200,unassigned_transcript_261,KEH14_r02,NC_014295.1,-,1,1328,0,0,0,NaN,...,rRNA,NaN,NaN,KEH14_r02,NaN,16S ribosomal RNA,NaN,l-rRNA,NaN,rRNA
35201,unassigned_transcript_262,KEH14_t22,NC_014295.1,-,1,67,0,0,0,NaN,...,tRNA,NaN,NaN,KEH14_t22,NaN,NaN,NaN,tRNA-Val,NaN,tRNA
35202,unassigned_transcript_263,KEH14_r01,NC_014295.1,-,1,786,0,0,0,NaN,...,rRNA,NaN,NaN,KEH14_r01,NaN,12S ribosomal RNA,NaN,s-rRNA,NaN,rRNA

In [5]:
Acer_info.columns

Index(['tx_name', 'gene_id', 'chrom', 'strand', 'nexon', 'tx_len', 'cds_len',
       'utr5_len', 'utr3_len', 'anticodon', 'codons', 'db_xref', 'deleted',
       'exception', 'experiment', 'gbkey', 'gene', 'inference', 'locus_tag',
       'model_evidence', 'note', 'partial', 'product', 'protein_id',
       'transcript_biotype'],
      dtype='str')

In [6]:
"gene_biotype" in Acer_info.columns

False

"gene_biotype" not in GTF ?!

In [7]:
Acer_info["transcript_biotype"].unique() # no "protein_coding" in transcript_biotype

<ArrowStringArray>
['mRNA', 'transcript', 'lnc_RNA', 'tRNA', 'snoRNA', 'snRNA', 'rRNA', 'ncRNA']
Length: 8, dtype: str

After verification, I found that the GTF did indeed have a gene_biotype column, but it only appeared in the first row of all rows corresponding to each gene_id:

![Acer](../.image/Pasted%20image%2020260503151005.png)

For comparison, *A. mellifera*'s reference GTF:

![Amel](../.image/Pasted%20image%2020260503151300.png)

To ensure the generality of the process (i.e., [2_make-ref.sh](../2_make-ref.sh) filters for `gene_biotype` rather than `transcript_biotype`), I need to fill in the missing `gene_biotype` values ​​in each line of the current GTF file.

In [79]:
from gtfparse import read_gtf

Acer_df = read_gtf("./ref/GCF_029169275.1_AcerK_1.0_genomic_corrected.gtf")
Acer_df = Acer_df.to_pandas()

INFO:root:Extracted GTF attributes: ['gene_id', 'db_xref', 'description', 'gbkey', 'gene', 'gene_biotype', 'transcript_id', 'experiment', 'model_evidence', 'product', 'transcript_biotype', 'exon_number', 'protein_id', 'part', 'anticodon', 'inference', 'note', 'exception', 'pseudo', 'transl_except', 'gene_synonym', 'partial', 'deleted', 'substituted', 'locus_tag', 'codons', 'transl_table']

In [82]:
print((Acer_df["gene_biotype"] != "").sum())
print(Acer_df["gene_id"].nunique())

13145
13145

↑ There is as many rows of non-empty `gene_biotype` as there are `gene_ids`. In other words, in each of the rows corresponding to a `gene_id`, there is one row of non-empty `gene_biotype`.

↓ within each `gene_id` group where only one row has a non-empty `gene_biotype` and the rest are empty strings, fill all rows of that group with that single non-empty value.

My approach was to manually parse and modify the GTF file. The original method involved using gtfparse to read the file, then filling in the `gene_biotype` field, and finally writing it as a GTF file using pyranges (because pyranges cannot read it directly). However, I later discovered this approach didn't work because gtfparse would parse the sixth column (`score`) of the GTF file as null (in GTF, its content is `.`), and it would also parse all the `.` in the eighth column (`frame`) as 0. As a result, when pyranges wrote the file as GTF, `cellranger mkref` couldn't parse it at all.

In [65]:
import re
from collections import defaultdict

In [71]:
INPUT_GTF  = "./ref/GCF_029169275.1_AcerK_1.0_genomic_corrected.gtf"
OUTPUT_GTF = "./ref/GCF_029169275.1_fixed.gtf"

In [69]:
# ── 第一步：解析GTF，原样保留每一行 ──────────────────────────────────────────

def parse_attributes(attr_str):
    """将attribute字符串解析为有序列表[(key, value), ...]，完整保留原始内容"""
    result = []
    for kv in attr_str.rstrip("; ").split("; "):
        kv = kv.strip()
        if not kv:
            continue
        parts = kv.split(" ", 1)
        if len(parts) == 2:
            key = parts[0]
            val = parts[1].strip('"')
            result.append((key, val))
    return result

def attributes_to_str(attr_list):
    """将[(key, value), ...]还原为GTF第9列字符串"""
    return "; ".join(f'{k} "{v}"' for k, v in attr_list) + ";"

In [72]:
# 读取所有行，保留注释行，解析数据行
header_lines = []
data_rows = []   # 每个元素: {"fields": [...8个字段...], "attrs": [(k,v),...]}

with open(INPUT_GTF, "r") as f:
    for line in f:
        line = line.rstrip("\n")
        if line.startswith("#"):
            header_lines.append(line)
            continue
        fields = line.split("\t")
        if len(fields) < 9:
            continue
        attrs = parse_attributes(fields[8])
        data_rows.append({
            "fields": fields[:8],   # 原样保留前8列，含"."不做任何转换
            "attrs":  attrs
        })

In [73]:
# ── 第二步：收集每个 gene_id 对应的 gene_biotype ──────────────────────────────

gene_biotype_map = {}   # gene_id → gene_biotype

for row in data_rows:
    feature = row["fields"][2]
    if feature != "gene":
        continue
    attr_dict = dict(row["attrs"])
    gid = attr_dict.get("gene_id", "")
    gbt = attr_dict.get("gene_biotype", "")
    if gid and gbt:
        gene_biotype_map[gid] = gbt

print(f"A total of {len(gene_biotype_map)} gene_ids and their corresponding gene_biotypes were collected.")

共收集到 13145 个 gene_id 的 gene_biotype

In [75]:
# ── 第三步：填充 gene_biotype，并写出 GTF ─────────────────────────────────────

filled_count = 0

with open(OUTPUT_GTF, "w") as out:
    # 写文件头
    for h in header_lines:
        out.write(h + "\n")

    for row in data_rows:
        fields  = row["fields"]
        attrs   = row["attrs"]     # [(key, val), ...]
        feature = fields[2]

        attr_dict = dict(attrs)
        gene_id   = attr_dict.get("gene_id", "")

        # 非gene行，且缺少gene_biotype，且能查到对应值 → 填充
        if (feature != "gene"
                and "gene_biotype" not in attr_dict
                and gene_id in gene_biotype_map):

            # 插入位置：紧跟在 gene_id 之后（或追加到末尾）
            new_attrs = []
            inserted  = False
            for k, v in attrs:
                new_attrs.append((k, v))
                if k == "gene_id" and not inserted:
                    new_attrs.append(("gene_biotype", gene_biotype_map[gene_id]))
                    inserted = True
            if not inserted:
                new_attrs.append(("gene_biotype", gene_biotype_map[gene_id]))
            attrs = new_attrs
            filled_count += 1

        attr_str = attributes_to_str(attrs)
        out.write("\t".join(fields) + "\t" + attr_str + "\n")

print(f"A total of {filled_count} rows of gene_biotype were populated.")

共填充了 711960 行的 gene_biotype
输出文件：./ref/GCF_029169275.1_fixed.gtf

In [86]:
Acer_df_modified = read_gtf("./ref/GCF_029169275.1_fixed.gtf")
Acer_df_modified = Acer_df_modified.to_pandas()

INFO:root:Extracted GTF attributes: ['gene_id', 'db_xref', 'description', 'gbkey', 'gene', 'gene_biotype', 'transcript_id', 'experiment', 'model_evidence', 'product', 'transcript_biotype', 'exon_number', 'protein_id', 'part', 'anticodon', 'inference', 'note', 'exception', 'pseudo', 'transl_except', 'gene_synonym', 'partial', 'deleted', 'substituted', 'locus_tag', 'codons', 'transl_table']

In [84]:
"gene_biotype" in Acer_df_modified.columns

True

In [89]:
print(f"unique gene_id number: {Acer_df_modified["gene_id"].nunique()}")
print(f"null gene_id number: {(Acer_df_modified["gene_id"] == "").sum()}")
print(f"null transcript_id number: {(Acer_df_modified["transcript_id"] == "").sum()}") # 13145, only null in the gene (not in transcript or exon) line
print(f"null gene_biotype number: {(Acer_df_modified["gene_biotype"] == "").sum()}")
print(f"null transcript_biotype number:{(Acer_df_modified["transcript_biotype"] == "").sum()}")
print(f"null exon_number number: {(Acer_df_modified["exon_number"] == "").sum()}")
print(f"null gene number: {(Acer_df_modified["gene"] == "").sum()}")

# print((Acer_df["pseudo"] == "").sum())

unique gene_id number: 13145
null gene_id number: 0
null transcript_id number: 13145
null gene_biotype number: 0
null transcript_biotype number:352540
null exon_number number: 48348
null gene number: 72

In [90]:
Acer_df_modified["gene_biotype"].unique()

<ArrowStringArray>
['protein_coding',         'lncRNA',       'misc_RNA',           'tRNA',
         'snoRNA',          'snRNA',     'pseudogene',           'rRNA',
          'ncRNA']
Length: 9, dtype: str

In [91]:
%%bash

gppy txinfo -g "./ref/GCF_029169275.1_fixed.gtf" > "./metadata/Acer_txinfo.tsv"

In [92]:
import pandas as pd

Acer_txinfo = pd.read_csv("./metadata/Acer_txinfo.tsv", sep="\t")
Acer_txinfo

/tmp/ipykernel_76250/521388490.py:3: DtypeWarning: Columns (0: codons, 1: locus_tag) have mixed types. Specify dtype option on import or set low_memory=False.
  Acer_txinfo = pd.read_csv("./metadata/Acer_txinfo.tsv", sep="\t")

,tx_name,gene_id,chrom,strand,nexon,tx_len,cds_len,utr5_len,utr3_len,anticodon,...,gene,gene_biotype,inference,locus_tag,model_evidence,note,partial,product,protein_id,transcript_biotype
0,XM_017048878.3,LOC107992807,NC_083852.1,-,6,713,312,197,204,NaN,...,LOC107992807,protein_coding,NaN,NaN,Supporting evidence includes similarity to: 13...,NaN,NaN,"ubiquitin-related modifier 1, transcript varia...",XP_016904367.1,mRNA
1,XM_017048879.3,LOC107992807,NC_083852.1,-,5,1167,312,651,204,NaN,...,LOC107992807,protein_coding,NaN,NaN,Supporting evidence includes similarity to: 14...,NaN,NaN,"ubiquitin-related modifier 1, transcript varia...",XP_016904368.1,mRNA
2,XM_062082541.1,LOC107992805,NC_083852.1,+,6,4095,3759,155,181,NaN,...,LOC107992805,protein_coding,NaN,NaN,Supporting evidence includes similarity to: 2 ...,NaN,NaN,MATH and LRR domain-containing protein PFE0570...,XP_061938525.1,mRNA
3,XM_062082566.1,LOC107992805,NC_083852.1,+,7,4344,3717,446,181,NaN,...,LOC107992805,protein_coding,NaN,NaN,Supporting evidence includes similarity to: 1 ...,NaN,NaN,MATH and LRR domain-containing protein PFE0570...,XP_061938550.1,mRNA
4,XM_062082576.1,LOC107992805,NC_083852.1,+,7,4339,3675,483,181,NaN,...,LOC107992805,protein_coding,NaN,NaN,Supporting evidence includes similarity to: 1 ...,NaN,NaN,MATH and LRR domain-containing protein PFE0570...,XP_061938560.1,mRNA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35198,unassigned_transcript_259,KEH14_p01,NC_014295.1,-,1,915,915,0,0,NaN,...,ND1,protein_coding,NaN,KEH14_p01,NaN,NaN,NaN,NaN,YP_003735181.1,mRNA
35199,unassigned_transcript_260,KEH14_t21,NC_014295.1,-,1,69,0,0,0,NaN,...,NaN,tRNA,NaN,KEH14_t21,NaN,NaN,NaN,tRNA-Leu,NaN,tRNA
35200,unassigned_transcript_261,KEH14_r02,NC_014295.1,-,1,1328,0,0,0,NaN,...,NaN,rRNA,NaN,KEH14_r02,NaN,16S ribosomal RNA,NaN,l-rRNA,NaN,rRNA
35201,unassigned_transcript_262,KEH14_t22,NC_014295.1,-,1,67,0,0,0,NaN,...,NaN,tRNA,NaN,KEH14_t22,NaN,NaN,NaN,tRNA-Val,NaN,tRNA
35202,unassigned_transcript_263,KEH14_r01,NC_014295.1,-,1,786,0,0,0,NaN,...,NaN,rRNA,NaN,KEH14_r01,NaN,12S ribosomal RNA,NaN,s-rRNA,NaN,rRNA

In [93]:
utr5_missing = ((Acer_txinfo["utr5_len"] == 0) & 
                (Acer_txinfo["gene_biotype"] == 'protein_coding')).sum() / \
               (Acer_txinfo["gene_biotype"] == 'protein_coding').sum()
print(utr5_missing)

0.07753922920359793

In [94]:
utr3_missing = ((Acer_txinfo["utr3_len"] == 0) & 
                (Acer_txinfo["gene_biotype"] == 'protein_coding')).sum() / \
               (Acer_txinfo["gene_biotype"] == 'protein_coding').sum()
print(utr3_missing)

0.05019368393408181

In [95]:
both_missing = ((Acer_txinfo["utr3_len"] == 0) & 
                (Acer_txinfo["utr5_len"] == 0) &
                (Acer_txinfo["gene_biotype"] == 'protein_coding')).sum() / \
               (Acer_txinfo["gene_biotype"] == 'protein_coding').sum()
print(both_missing)

0.046812422034009586

In [96]:
either_missing = (((Acer_txinfo["utr3_len"] == 0) | (Acer_txinfo["utr5_len"] == 0)) & # 注意!! 必须将 | 括起来, 因为 & 的优先级比 | 大
                (Acer_txinfo["gene_biotype"] == 'protein_coding')).sum() / \
               (Acer_txinfo["gene_biotype"] == 'protein_coding').sum()
print(either_missing)

0.08092049110367015